# QQ机器人登录协议指南
Write-Host "QQ机器人登录协议指南"
Write-Host "===================="
Write-Host ""
Write-Host "错误分析："
Write-Host "从Terminal#181-183可以看到，尝试使用'ANDROID_PHONE_8.1'协议登录失败"
Write-Host "错误信息：无法解析 ANDROID_PHONE_8.1 为 MiraiProtocol"
Write-Host ""
Write-Host "问题原因："
Write-Host "Mirai Console不支持'ANDROID_PHONE_8.1'这样的协议格式"
Write-Host "正确的协议格式应该是标准协议名称，不包含版本号"
Write-Host ""
Write-Host "正确的登录命令："
Write-Host "------------------------------------------"
Write-Host "login 3406280693 Leslie.1 ANDROID_PHONE"
Write-Host "------------------------------------------"
Write-Host ""
Write-Host "可用的标准协议列表："
Write-Host "- ANDROID_PHONE （推荐）"
Write-Host "- ANDROID_PAD"
Write-Host "- ANDROID_WATCH"
Write-Host "- IPAD"
Write-Host "- MACOS"
Write-Host ""
Write-Host "使用说明："
Write-Host "1. 在Mirai Console终端中直接复制正确的登录命令"
Write-Host "2. 登录过程中可能需要完成验证码验证"
Write-Host "3. 若一个协议登录失败，可以尝试其他协议"
Write-Host ""
Write-Host "直接登录选项："
Write-Host "您可以直接在PowerShell中运行以下命令发送登录指令："
Write-Host "echo 'login 3406280693 Leslie.1 ANDROID_PHONE' | .\mcl"