# QQ机器人功能验证脚本

Write-Host "QQ机器人功能验证脚本"
Write-Host "======================="
Write-Host ""
Write-Host "验证步骤:"
Write-Host "1. 请确保Mirai Console已启动并运行"
Write-Host "2. 在Mirai Console终端中执行登录命令:"
Write-Host "   login 3406280693 Leslie.1 ANDROID_PHONE"
Write-Host "3. 登录成功后，可以测试以下功能:"
Write-Host ""
Write-Host "功能测试命令:"
Write-Host "----------------------------------------"
Write-Host "- 发送消息: send 好友QQ号 你好，这是测试消息"
Write-Host "- 查看在线状态: status"
Write-Host "- 列出插件: plugins"
Write-Host "- 退出登录: logout 3406280693"
Write-Host "----------------------------------------"
Write-Host ""
Write-Host "常见问题排查:"
Write-Host "- 验证码问题: 确保sakura插件已正确加载"
Write-Host "- 协议错误: 尝试其他协议，如ANDROID_PAD或IPAD"
Write-Host "- 登录失败: 检查账号密码是否正确，或是否被限制登录"
Write-Host ""
Write-Host "sakura插件验证:"
Write-Host "在Mirai Console中输入 'plugins' 命令，查看插件列表中是否包含'sakura'"