# QQ机器人快速登录脚本
# 使用正确的协议登录QQ机器人

Write-Host "QQ机器人快速登录脚本"
Write-Host "======================="
Write-Host "账号: 3406280693"
Write-Host "密码: Leslie.1"
Write-Host "推荐协议: ANDROID_PHONE"
Write-Host ""
Write-Host "请在Mirai Console终端中直接复制以下命令执行登录:"
Write-Host "------------------------------------------"
Write-Host "login 3406280693 Leslie.1 ANDROID_PHONE"
Write-Host "------------------------------------------"
Write-Host ""
Write-Host "可用的标准协议列表:"
Write-Host "- ANDROID_PHONE"
Write-Host "- ANDROID_PAD"
Write-Host "- ANDROID_WATCH"
Write-Host "- IPAD"
Write-Host "- MACOS"
Write-Host ""
Write-Host "注意: 登录过程中可能需要完成验证码，请在终端中按照提示操作。"
Write-Host "若遇到协议错误，请尝试切换其他协议。"