# -*- coding: utf-8 -*-
"""饮料类商品 (type=drink)。

所有饮品在此集中管理，按 id 字典导出 DRINKS。
其他类别见 snacks.py (零食) / meals.py (正餐)。
"""
from .models import FoodItem, NutritionProfile, TasteProfile

DRINKS: dict[str, FoodItem] = {
    "water": FoodItem(
        id="water",
        name="纯净水",
        description="最纯净的水源，补充水分。",
        price=10,
        type="drink",
        icon="💧",
        nutrition=NutritionProfile(hunger=0, thirst=40, energy=0),
        taste=TasteProfile(),
    ),
    "coffee": FoodItem(
        id="coffee",
        name="浓缩咖啡",
        description="提神醒脑，但是喝多了会心悸。",
        price=35,
        type="drink",
        icon="☕",
        nutrition=NutritionProfile(hunger=2, thirst=15, energy=25, health=-1),
        taste=TasteProfile(bitter=0.8, sour=0.2, temperature="hot"),
        buff_desc="提神：短期内能量回复速度提升",
    ),
    "bubble_tea": FoodItem(
        id="bubble_tea",
        name="珍珠奶茶",
        description="甜甜的快乐水，心情变好！",
        price=45,
        type="drink",
        icon="🧋",
        nutrition=NutritionProfile(hunger=10, thirst=20, energy=15, health=-2),
        taste=TasteProfile(sweet=0.9, temperature="cold"),
        buff_desc="多巴胺：心情值大幅提升",
    ),
    "cola": FoodItem(
        id="cola",
        name="冰镇可乐",
        description="肥宅快乐水，二氧化碳的冲击！",
        price=25,
        type="drink",
        icon="🥤",
        nutrition=NutritionProfile(hunger=5, thirst=30, energy=10, health=-2),
        taste=TasteProfile(sweet=0.8, temperature="cold"),
    ),
    "green_tea": FoodItem(
        id="green_tea",
        name="手打抹茶",
        description="清新的茶香，平复心情。",
        price=30,
        type="drink",
        icon="🍵",
        nutrition=NutritionProfile(hunger=0, thirst=35, energy=5, health=2),
        taste=TasteProfile(bitter=0.4, umami=0.3, temperature="hot"),
        min_level=3,
    ),
    "energy_drink": FoodItem(
        id="energy_drink",
        name="怪兽能量",
        description="释放野性！高浓度咖啡因与牛磺酸。",
        price=50,
        type="drink",
        icon="🔋",
        nutrition=NutritionProfile(hunger=0, thirst=20, energy=50, health=-5),
        taste=TasteProfile(sweet=0.6, sour=0.3, temperature="cold"),
        min_level=10,
        rarity="rare",
        buff_desc="超负荷：极大能量补充，但会导致后续疲劳",
    ),
    "soy_milk": FoodItem(
        id="soy_milk",
        name="热豆浆",
        description="清晨能量补给，暖胃又舒服。",
        price=22,
        type="drink",
        icon="🥛",
        nutrition=NutritionProfile(hunger=8, thirst=25, energy=12, health=3),
        taste=TasteProfile(sweet=0.3, umami=0.2, temperature="hot"),
    ),
    "fruit_tea": FoodItem(
        id="fruit_tea",
        name="鲜果茶",
        description="酸甜清爽，补水同时提提神。",
        price=32,
        type="drink",
        icon="🍹",
        nutrition=NutritionProfile(hunger=5, thirst=30, energy=8, health=1),
        taste=TasteProfile(sweet=0.5, sour=0.4, temperature="cold"),
    ),
    "mulled_wine": FoodItem(
        id="mulled_wine",
        name="热红酒",
        description="圣诞节的肉桂橙香，微醺的暖意。",
        price=68,
        type="drink",
        icon="🍷",
        nutrition=NutritionProfile(hunger=10, thirst=20, energy=30, health=-2),
        taste=TasteProfile(sweet=0.5, bitter=0.3, temperature="hot"),
        min_level=8,
        rarity="rare",
        buff_desc="节日微醺：心情大幅提升，但精力会有所下降",
    ),
}
