# -*- coding: utf-8 -*-
"""正餐类商品 (type=meal)。

包含所有正餐、汤类、粥类、早茶主食、地方特色、国际菜、夜宵主食、节日正餐。
其他类别见 drinks.py (饮料) / snacks.py (零食)。
"""
from .models import FoodItem, NutritionProfile, TasteProfile

MEALS: dict[str, FoodItem] = {
    "sandwich": FoodItem(
        id="sandwich",
        name="全麦三明治",
        description="健康的午餐选择，营养均衡。",
        price=55,
        type="meal",
        icon="🥪",
        nutrition=NutritionProfile(hunger=50, thirst=0, energy=15, health=5),
        taste=TasteProfile(salty=0.3, umami=0.4),
    ),
    "ramen": FoodItem(
        id="ramen",
        name="豚骨拉面",
        description="浓郁的汤底，劲道的面条，温暖灵魂。",
        price=85,
        type="meal",
        icon="🍜",
        nutrition=NutritionProfile(hunger=70, thirst=10, energy=25, health=2),
        taste=TasteProfile(salty=0.6, umami=0.9, temperature="hot"),
        min_level=4,
    ),
    "burger": FoodItem(
        id="burger",
        name="双层吉士堡",
        description="大口吃肉的快感，热量爆炸！",
        price=75,
        type="meal",
        icon="🍔",
        nutrition=NutritionProfile(hunger=80, thirst=-10, energy=30, health=-4),
        taste=TasteProfile(salty=0.7, umami=0.8, temperature="hot"),
        min_level=3,
    ),
    "pizza": FoodItem(
        id="pizza",
        name="意式披萨",
        description="拉丝的芝士，丰富的配料，分享的快乐。",
        price=110,
        type="meal",
        icon="🍕",
        nutrition=NutritionProfile(hunger=85, thirst=-15, energy=25, health=-3),
        taste=TasteProfile(salty=0.6, umami=0.7, temperature="hot"),
        min_level=6,
        rarity="rare",
    ),
    "steak": FoodItem(
        id="steak",
        name="惠灵顿牛排",
        description="顶级的食材，极致的烹饪，尊贵的体验。",
        price=280,
        type="meal",
        icon="🥩",
        nutrition=NutritionProfile(hunger=100, thirst=-20, energy=40, health=10),
        taste=TasteProfile(salty=0.5, umami=1.0, temperature="hot"),
        min_level=15,
        rarity="epic",
        buff_desc="顶级盛宴：所有属性大幅提升，获得长期满足感",
    ),
    "hotpot": FoodItem(
        id="hotpot",
        name="麻辣火锅",
        description="没有什么是一顿火锅解决不了的。",
        price=120,
        type="meal",
        icon="🍲",
        nutrition=NutritionProfile(hunger=90, thirst=-30, energy=20, health=-5),
        taste=TasteProfile(spicy=1.0, salty=0.8, umami=0.9, temperature="hot"),
        min_level=5,
    ),
    "sushi": FoodItem(
        id="sushi",
        name="高级寿司",
        description="新鲜的食材，精致的享受。",
        price=150,
        type="meal",
        icon="🍣",
        nutrition=NutritionProfile(hunger=60, thirst=0, energy=10, health=8),
        taste=TasteProfile(umami=0.8, sweet=0.2, temperature="cold"),
        min_level=8,
    ),
    "salad": FoodItem(
        id="salad",
        name="健身沙拉",
        description="低脂健康，为了更好的身材。",
        price=45,
        type="meal",
        icon="🥗",
        nutrition=NutritionProfile(hunger=35, thirst=15, energy=10, health=12),
        taste=TasteProfile(sour=0.4, umami=0.2, temperature="room"),
        min_level=2,
    ),
    "fried_rice": FoodItem(
        id="fried_rice",
        name="蛋炒饭",
        description="经典碳水补给，稳定续航。",
        price=68,
        type="meal",
        icon="🍚",
        nutrition=NutritionProfile(hunger=72, thirst=-5, energy=20, health=2),
        taste=TasteProfile(salty=0.5, umami=0.6, temperature="hot"),
    ),
    "beef_noodle": FoodItem(
        id="beef_noodle",
        name="红烧牛肉面",
        description="汤浓肉香，满足感拉满。",
        price=98,
        type="meal",
        icon="🍜",
        nutrition=NutritionProfile(hunger=82, thirst=6, energy=24, health=4),
        taste=TasteProfile(salty=0.7, umami=0.9, temperature="hot"),
        rarity="rare",
    ),
    "tomato_egg_soup": FoodItem(
        id="tomato_egg_soup",
        name="番茄蛋汤",
        description="家常暖汤，酸甜开胃。",
        price=28,
        type="meal",
        icon="🥣",
        nutrition=NutritionProfile(hunger=35, thirst=30, energy=8, health=4),
        taste=TasteProfile(sour=0.4, umami=0.5, temperature="hot"),
    ),
    "miso_soup": FoodItem(
        id="miso_soup",
        name="味噌汤",
        description="日式经典，温润鲜美。",
        price=32,
        type="meal",
        icon="🍲",
        nutrition=NutritionProfile(hunger=30, thirst=35, energy=6, health=5),
        taste=TasteProfile(salty=0.4, umami=0.6, temperature="hot"),
        min_level=2,
    ),
    "borscht": FoodItem(
        id="borscht",
        name="罗宋汤",
        description="俄罗斯浓汤，甜菜根的瑰丽色泽。",
        price=58,
        type="meal",
        icon="🥘",
        nutrition=NutritionProfile(hunger=55, thirst=25, energy=15, health=6),
        taste=TasteProfile(sour=0.5, salty=0.4, umami=0.5, temperature="hot"),
        min_level=4,
        rarity="rare",
    ),
    "tom_yum": FoodItem(
        id="tom_yum",
        name="冬阴功汤",
        description="酸辣鲜香，一口穿越到曼谷。",
        price=75,
        type="meal",
        icon="🍋",
        nutrition=NutritionProfile(hunger=50, thirst=40, energy=18, health=3),
        taste=TasteProfile(sour=0.8, spicy=0.7, umami=0.7, temperature="hot"),
        min_level=6,
        rarity="rare",
        buff_desc="东南亚风情：酸辣刺激，瞬间唤醒感官",
    ),
    "congee_pork": FoodItem(
        id="congee_pork",
        name="皮蛋瘦肉粥",
        description="广式早茶经典，温润绵滑。",
        price=42,
        type="meal",
        icon="🍚",
        nutrition=NutritionProfile(hunger=55, thirst=20, energy=12, health=6),
        taste=TasteProfile(salty=0.4, umami=0.6, temperature="hot"),
    ),
    "seafood_congee": FoodItem(
        id="seafood_congee",
        name="海鲜砂锅粥",
        description="鲜得掉眉毛，慢熬出真味。",
        price=88,
        type="meal",
        icon="🦐",
        nutrition=NutritionProfile(hunger=70, thirst=20, energy=18, health=8),
        taste=TasteProfile(salty=0.4, umami=0.9, temperature="hot"),
        min_level=5,
        rarity="rare",
    ),
    "millet_porridge": FoodItem(
        id="millet_porridge",
        name="小米南瓜粥",
        description="养胃轻食，金黄温润。",
        price=28,
        type="meal",
        icon="🥣",
        nutrition=NutritionProfile(hunger=40, thirst=20, energy=10, health=8),
        taste=TasteProfile(sweet=0.3, umami=0.2, temperature="hot"),
    ),
    "jianbing": FoodItem(
        id="jianbing",
        name="煎饼果子",
        description="街头早餐之王，脆饼裹住世界。",
        price=22,
        type="meal",
        icon="🥞",
        nutrition=NutritionProfile(hunger=55, thirst=-5, energy=18, health=1),
        taste=TasteProfile(salty=0.6, umami=0.5, temperature="hot"),
    ),
    "peking_duck": FoodItem(
        id="peking_duck",
        name="北京烤鸭",
        description="皮酥肉嫩，蘸甜面酱卷葱黄瓜丝。",
        price=198,
        type="meal",
        icon="🦆",
        nutrition=NutritionProfile(hunger=95, thirst=-5, energy=35, health=5),
        taste=TasteProfile(salty=0.5, sweet=0.3, umami=1.0, temperature="hot"),
        min_level=10,
        rarity="epic",
        buff_desc="京味盛宴：满足感拉满，情绪大幅提升",
    ),
    "mapo_tofu": FoodItem(
        id="mapo_tofu",
        name="麻婆豆腐",
        description="麻辣鲜香，下饭神器。",
        price=58,
        type="meal",
        icon="🌶️",
        nutrition=NutritionProfile(hunger=65, thirst=-10, energy=18, health=2),
        taste=TasteProfile(spicy=0.9, salty=0.6, umami=0.8, temperature="hot"),
        min_level=3,
    ),
    "lanzhou_noodle": FoodItem(
        id="lanzhou_noodle",
        name="兰州牛肉拉面",
        description="一清二白三红四绿五黄。",
        price=58,
        type="meal",
        icon="🍜",
        nutrition=NutritionProfile(hunger=78, thirst=10, energy=22, health=4),
        taste=TasteProfile(salty=0.6, spicy=0.4, umami=0.8, temperature="hot"),
        min_level=2,
    ),
    "hui_guo_rou": FoodItem(
        id="hui_guo_rou",
        name="回锅肉",
        description="川菜之王，肥而不腻。",
        price=72,
        type="meal",
        icon="🥓",
        nutrition=NutritionProfile(hunger=80, thirst=-8, energy=25, health=-2),
        taste=TasteProfile(spicy=0.6, salty=0.7, umami=0.8, temperature="hot"),
        min_level=5,
    ),
    "pasta": FoodItem(
        id="pasta",
        name="意式肉酱面",
        description="浓郁番茄肉酱裹满每一根面条。",
        price=78,
        type="meal",
        icon="🍝",
        nutrition=NutritionProfile(hunger=75, thirst=-5, energy=22, health=3),
        taste=TasteProfile(salty=0.5, sour=0.4, umami=0.7, temperature="hot"),
        min_level=3,
    ),
    "green_curry": FoodItem(
        id="green_curry",
        name="泰式绿咖喱鸡",
        description="椰香与香茅交织的异域风情。",
        price=92,
        type="meal",
        icon="🍛",
        nutrition=NutritionProfile(hunger=70, thirst=5, energy=20, health=4),
        taste=TasteProfile(spicy=0.7, sweet=0.4, umami=0.7, temperature="hot"),
        min_level=6,
        rarity="rare",
    ),
    "bibimbap": FoodItem(
        id="bibimbap",
        name="韩国石锅拌饭",
        description="滋滋作响，拌出五彩斑斓。",
        price=72,
        type="meal",
        icon="🍲",
        nutrition=NutritionProfile(hunger=75, thirst=0, energy=18, health=6),
        taste=TasteProfile(salty=0.5, spicy=0.5, umami=0.7, temperature="hot"),
        min_level=4,
    ),
    "japanese_curry": FoodItem(
        id="japanese_curry",
        name="日式咖喱饭",
        description="浓郁微甜，治愈系暖食。",
        price=68,
        type="meal",
        icon="🍛",
        nutrition=NutritionProfile(hunger=78, thirst=-5, energy=20, health=3),
        taste=TasteProfile(sweet=0.4, salty=0.5, umami=0.7, temperature="hot"),
        min_level=2,
    ),
    "taco": FoodItem(
        id="taco",
        name="墨西哥塔可",
        description="脆皮裹住色彩斑斓的内馅。",
        price=55,
        type="meal",
        icon="🌮",
        nutrition=NutritionProfile(hunger=60, thirst=-5, energy=15, health=4),
        taste=TasteProfile(spicy=0.5, sour=0.4, salty=0.5, temperature="room"),
        min_level=4,
    ),
    "pho": FoodItem(
        id="pho",
        name="越南河粉",
        description="清汤慢熬，挤一片青柠鲜活整碗。",
        price=65,
        type="meal",
        icon="🍜",
        nutrition=NutritionProfile(hunger=70, thirst=20, energy=15, health=6),
        taste=TasteProfile(salty=0.4, sour=0.3, umami=0.7, temperature="hot"),
        min_level=3,
    ),
    "malatang": FoodItem(
        id="malatang",
        name="麻辣烫",
        description="自选食材的青春汤锅，辣到冒汗。",
        price=58,
        type="meal",
        icon="🌶️",
        nutrition=NutritionProfile(hunger=70, thirst=-20, energy=18, health=-2),
        taste=TasteProfile(spicy=0.9, salty=0.6, umami=0.8, temperature="hot"),
        min_level=3,
    ),
    "instant_noodle": FoodItem(
        id="instant_noodle",
        name="深夜泡面",
        description="凌晨两点的精神食粮。",
        price=18,
        type="meal",
        icon="🍜",
        nutrition=NutritionProfile(hunger=55, thirst=-10, energy=10, health=-4),
        taste=TasteProfile(salty=0.7, umami=0.7, temperature="hot"),
        buff_desc="夜食慰藉：临时饱腹但睡眠质量略降",
    ),
    "zongzi": FoodItem(
        id="zongzi",
        name="蛋黄肉粽",
        description="端午限定，糯米裹住咸蛋黄与五花肉。",
        price=42,
        type="meal",
        icon="🍙",
        nutrition=NutritionProfile(hunger=70, thirst=-5, energy=18, health=2),
        taste=TasteProfile(salty=0.6, umami=0.7, temperature="hot"),
        rarity="rare",
    ),
    "dumpling": FoodItem(
        id="dumpling",
        name="手工水饺",
        description="冬至过年必备，蘸醋更香。",
        price=45,
        type="meal",
        icon="🥟",
        nutrition=NutritionProfile(hunger=65, thirst=0, energy=15, health=5),
        taste=TasteProfile(salty=0.5, umami=0.7, temperature="hot"),
    ),
}
