# -*- coding: utf-8 -*-
"""零食/小吃类商品 (type=snack)。

所有零食、甜点、下午茶、夜宵小食、节日限定小食在此集中管理。
其他类别见 drinks.py (饮料) / meals.py (正餐)。
"""
from .models import FoodItem, NutritionProfile, TasteProfile

SNACKS: dict[str, FoodItem] = {
    "cookie": FoodItem(
        id="cookie",
        name="巧克力曲奇",
        description="酥脆的口感，浓郁的巧克力味。",
        price=20,
        type="snack",
        icon="🍪",
        nutrition=NutritionProfile(hunger=15, thirst=-5, energy=10),
        taste=TasteProfile(sweet=0.7, bitter=0.1),
    ),
    "spicy_stick": FoodItem(
        id="spicy_stick",
        name="辣条",
        description="来自东方的神秘零食，非常刺激。",
        price=15,
        type="snack",
        icon="🌶️",
        nutrition=NutritionProfile(hunger=10, thirst=-10, energy=5, health=-3),
        taste=TasteProfile(spicy=0.9, salty=0.6, umami=0.4),
    ),
    "chips": FoodItem(
        id="chips",
        name="薯片",
        description="咔嚓咔嚓，根本停不下来。",
        price=18,
        type="snack",
        icon="🍟",
        nutrition=NutritionProfile(hunger=12, thirst=-15, energy=5, health=-2),
        taste=TasteProfile(salty=0.8, umami=0.5),
    ),
    "cake": FoodItem(
        id="cake",
        name="草莓蛋糕",
        description="精致的甜点，治愈一切不开心。",
        price=65,
        type="snack",
        icon="🍰",
        nutrition=NutritionProfile(hunger=30, thirst=-5, energy=20, health=-1),
        taste=TasteProfile(sweet=1.0, temperature="cold"),
        min_level=5,
        rarity="rare",
    ),
    "pudding": FoodItem(
        id="pudding",
        name="焦糖布丁",
        description="Q弹顺滑，入口即化。",
        price=35,
        type="snack",
        icon="🍮",
        nutrition=NutritionProfile(hunger=15, thirst=5, energy=10),
        taste=TasteProfile(sweet=0.8, temperature="cold"),
        min_level=3,
    ),
    "ice_cream": FoodItem(
        id="ice_cream",
        name="缤纷冰淇淋",
        description="夏天最棒的礼物，融化在舌尖。",
        price=40,
        type="snack",
        icon="🍦",
        nutrition=NutritionProfile(hunger=10, thirst=10, energy=15, health=-1),
        taste=TasteProfile(sweet=0.9, temperature="cold"),
        min_level=2,
    ),
    "nuts_mix": FoodItem(
        id="nuts_mix",
        name="坚果拼盘",
        description="高密度能量零食，抗饿小能手。",
        price=38,
        type="snack",
        icon="🥜",
        nutrition=NutritionProfile(hunger=25, thirst=-4, energy=18, health=4),
        taste=TasteProfile(salty=0.2, umami=0.3),
    ),
    "yogurt": FoodItem(
        id="yogurt",
        name="希腊酸奶杯",
        description="清爽顺滑，兼顾口感和健康。",
        price=30,
        type="snack",
        icon="🥣",
        nutrition=NutritionProfile(hunger=20, thirst=5, energy=8, health=5),
        taste=TasteProfile(sour=0.5, sweet=0.4, temperature="cold"),
    ),
    "xiaolongbao": FoodItem(
        id="xiaolongbao",
        name="小笼包",
        description="咬开一口汤，鲜得舌尖发烫。",
        price=48,
        type="snack",
        icon="🥟",
        nutrition=NutritionProfile(hunger=40, thirst=15, energy=12, health=3),
        taste=TasteProfile(salty=0.5, umami=0.8, temperature="hot"),
        min_level=2,
    ),
    "rice_noodle_roll": FoodItem(
        id="rice_noodle_roll",
        name="布拉肠粉",
        description="晶莹剔透，酱油香绕齿三日。",
        price=38,
        type="snack",
        icon="🍜",
        nutrition=NutritionProfile(hunger=35, thirst=10, energy=10, health=4),
        taste=TasteProfile(salty=0.5, umami=0.7, temperature="hot"),
    ),
    "tiramisu": FoodItem(
        id="tiramisu",
        name="提拉米苏",
        description="咖啡与马斯卡彭的浪漫二重唱。",
        price=58,
        type="snack",
        icon="🍰",
        nutrition=NutritionProfile(hunger=25, thirst=-5, energy=18, health=1),
        taste=TasteProfile(sweet=0.7, bitter=0.3, temperature="cold"),
        min_level=4,
        rarity="rare",
        buff_desc="意式甜梦：心情 +快乐，但咖啡因会少许影响睡眠",
    ),
    "macaron": FoodItem(
        id="macaron",
        name="马卡龙",
        description="少女的酥胸，色彩斑斓如梦。",
        price=48,
        type="snack",
        icon="🧁",
        nutrition=NutritionProfile(hunger=18, thirst=-8, energy=15, health=-1),
        taste=TasteProfile(sweet=1.0, temperature="room"),
        min_level=5,
        rarity="rare",
    ),
    "scone": FoodItem(
        id="scone",
        name="英式司康饼",
        description="配红茶的最佳搭档，松脆温润。",
        price=35,
        type="snack",
        icon="🥮",
        nutrition=NutritionProfile(hunger=28, thirst=-10, energy=12),
        taste=TasteProfile(sweet=0.4, salty=0.3, temperature="room"),
        min_level=3,
    ),
    "skewers": FoodItem(
        id="skewers",
        name="炭烤肉串",
        description="深夜的灵魂救赎，烟火气十足。",
        price=52,
        type="snack",
        icon="🍢",
        nutrition=NutritionProfile(hunger=50, thirst=-15, energy=15, health=-3),
        taste=TasteProfile(spicy=0.6, salty=0.7, umami=0.8, temperature="hot"),
        min_level=2,
    ),
    "tangyuan": FoodItem(
        id="tangyuan",
        name="黑芝麻汤圆",
        description="元宵节的甜蜜团圆。",
        price=32,
        type="snack",
        icon="🥣",
        nutrition=NutritionProfile(hunger=35, thirst=5, energy=15, health=2),
        taste=TasteProfile(sweet=0.9, temperature="hot"),
        rarity="rare",
        buff_desc="团圆甜意：心情大好，温暖的家感",
    ),
    "mooncake": FoodItem(
        id="mooncake",
        name="双黄莲蓉月饼",
        description="中秋限定，醇厚甜美。",
        price=55,
        type="snack",
        icon="🥮",
        nutrition=NutritionProfile(hunger=40, thirst=-15, energy=18, health=-2),
        taste=TasteProfile(sweet=0.9, salty=0.3, temperature="room"),
        rarity="rare",
        buff_desc="中秋情思：浓情蜜意，但热量爆炸",
    ),
    "watermelon": FoodItem(
        id="watermelon",
        name="冰镇西瓜",
        description="夏天的代言人，空调房里最爽。",
        price=25,
        type="snack",
        icon="🍉",
        nutrition=NutritionProfile(hunger=15, thirst=35, energy=5, health=4),
        taste=TasteProfile(sweet=0.8, temperature="cold"),
    ),
    "roasted_chestnut": FoodItem(
        id="roasted_chestnut",
        name="糖炒栗子",
        description="冬日街头的甜香，捧在手心暖暖的。",
        price=28,
        type="snack",
        icon="🌰",
        nutrition=NutritionProfile(hunger=35, thirst=-5, energy=15, health=4),
        taste=TasteProfile(sweet=0.5, umami=0.3, temperature="hot"),
    ),
}
