"""
主动关怀睡眠相关窗口与阈值

从原 `shared/constants.py` 拆出：只放晚安/低打扰/睡眠窗口判定用到的
时间阈值，与通用调度阈值（tuning.py）分开，方便调睡眠策略时只改这里。
纯数据模块，无 import 依赖。
"""

# ── 晚安低打扰 ──────────────────────────────────────────────
# 晚安后超过该小时数自动退出低打扰（避免卡死在低打扰）
AUTO_WAKE_MAX_HOURS = 14
# 晚安信号之间的最小间隔，用于合并重复晚安
GOODNIGHT_SIGNAL_GAP_SECONDS = 300
# 晚安后的初始静默时长
GOODNIGHT_INITIAL_QUIET_SECONDS = 1800
# 即使信息不全，也至少静默这么久
MIN_QUIET_EVEN_INCOMPLETE_SECONDS = 180
# sleep_hint 探针间隔（probable_sleep 移除后仍在使用）
PROBABLE_SLEEP_PROBE_GAP_SECONDS = 3600

# ── 作息自适应窗口（schedule_adapter 的沉默阈值学习）────────
PROBABLE_SLEEP_SILENCE_NIGHT_SECONDS = 7200
PROBABLE_SLEEP_SILENCE_MORNING_SECONDS = 10800
PROBABLE_SLEEP_SILENCE_EVENING_SECONDS = 3600
PROBABLE_SLEEP_NIGHT_HOUR_START = 0
PROBABLE_SLEEP_NIGHT_HOUR_END = 6
PROBABLE_SLEEP_MORNING_HOUR_START = 6
PROBABLE_SLEEP_MORNING_HOUR_END = 10
PROBABLE_SLEEP_EVENING_HOUR_START = 18
PROBABLE_SLEEP_EVENING_HOUR_END = 24


__all__ = [
    "AUTO_WAKE_MAX_HOURS",
    "GOODNIGHT_SIGNAL_GAP_SECONDS",
    "GOODNIGHT_INITIAL_QUIET_SECONDS",
    "MIN_QUIET_EVEN_INCOMPLETE_SECONDS",
    "PROBABLE_SLEEP_PROBE_GAP_SECONDS",
    "PROBABLE_SLEEP_SILENCE_NIGHT_SECONDS",
    "PROBABLE_SLEEP_SILENCE_MORNING_SECONDS",
    "PROBABLE_SLEEP_SILENCE_EVENING_SECONDS",
    "PROBABLE_SLEEP_NIGHT_HOUR_START",
    "PROBABLE_SLEEP_NIGHT_HOUR_END",
    "PROBABLE_SLEEP_MORNING_HOUR_START",
    "PROBABLE_SLEEP_MORNING_HOUR_END",
    "PROBABLE_SLEEP_EVENING_HOUR_START",
    "PROBABLE_SLEEP_EVENING_HOUR_END",
]
