"""
Persona System 模块

所有功能已迁移到 prompt/ 子目录，这里只保留向后兼容的重新导出
"""
from .prompt import (
    get_dialogue_examples,
    tokenize_for_example_rank,
    get_qq_master_id,
    extract_qq_user_id,
    apply_qq_optimizations,
    load_public_qq_prompt_template,
    resolve_user_name,
    resolve_user_name_from_persona_logic,
    get_context_injection,
    prepare_emotion_context,
    prepare_life_stats,
    determine_model_info,
    build_food_context_text,
    get_instruction_injection,
    get_study_folder_history_injection,
    determine_mode,
    check_sensitive_mode,
    get_contrastive_prompting_injection,
    get_style_guard,
    get_natural_dialogue_policy,
    get_special_day_prompt,
    get_upcoming_birthday_prompt,
    get_dynamic_system_prompt,
    build_expanded_persona_prompt,
    get_persona_name_from_filename,
)

__all__ = [
    "get_dialogue_examples",
    "tokenize_for_example_rank",
    "get_qq_master_id",
    "extract_qq_user_id",
    "apply_qq_optimizations",
    "load_public_qq_prompt_template",
    "resolve_user_name",
    "resolve_user_name_from_persona_logic",
    "get_context_injection",
    "prepare_emotion_context",
    "prepare_life_stats",
    "determine_model_info",
    "build_food_context_text",
    "get_instruction_injection",
    "get_study_folder_history_injection",
    "determine_mode",
    "check_sensitive_mode",
    "get_contrastive_prompting_injection",
    "get_style_guard",
    "get_natural_dialogue_policy",
    "get_special_day_prompt",
    "get_upcoming_birthday_prompt",
    "get_dynamic_system_prompt",
    "build_expanded_persona_prompt",
    "get_persona_name_from_filename",
]
