org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError

org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.warning.mode=summary

android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.enableR8.fullMode=true
android.suppressUnsupportedCompileSdk=35

kotlin.daemon.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
kotlin.code.style=official

# 规避 KSP 2.0.21-1.0.28 增量编译重复输出同一 Factory 类导致 "类重复" 编译失败
ksp.incremental=false
